name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Upload application files
        uses: actions/upload-artifact@v4
        with:
          name: app-files
          path: |
            index.js
            package.json
            package-lock.json
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    steps:
      - name: Download application files
        uses: actions/download-artifact@v4
        with:
          name: app-files

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$VM_HOST" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_HOST: ${{ secrets.VM_HOST }}

      - name: Deploy to VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          AZURE_USER: ${{ secrets.AZURE_USER }}
        run: |
          echo "Deploying to $VM_HOST..."
          scp -r index.js package*.json $AZURE_USER@$VM_HOST:~/node-app/
          ssh $AZURE_USER@$VM_HOST "cd ~/node-app && npm install --omit=dev && pm2 start index.js --name node-app --update-env || pm2 restart node-app"
